right_format = "$time"

[python]


[sudo]
disabled = false
style = "bold green"
symbol = ""

[status]
disabled = false
symbol = "âŒ "
not_executable_symbol = "ğŸš« "
sigint_symbol = "ğŸ›‘ "
not_found_symbol = "ğŸ” "
signal_symbol = "âš¡"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true


[time]
disabled = false
format = "ğŸ•™ [$time]($style) "
